version: build{build}
image: Visual Studio 2022
clone_folder: C:\CKli-World\CK-Database-Projects\CK-Sqlite
environment:
  CKSETUPREMOTESTORE_PUSH_API_KEY:
    secure: ffSyq7zhajO1GUXQraZnZiZGtrPjUMGXXhlS71JUDouxx43VgzbtRfqmZM6zKTmS
  CKSETUP_CAKE_TARGET_STORE_APIKEY_AND_URL:
    secure: ffSyq7zhajO1GUXQraZnZiZGtrPjUMGXXhlS71JUDos5aibfGQQ0zf4BWRjM02dn3zrvVnGZBp6bZwULB/ffASa7PO3mcKcqvppnG6eLYDU=
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
test: false
on_finish:
- ps: >-
    Write-Host "Collecting logs..."

    Get-ChildItem -Recurse *.log -Exclude LastRun.log -ErrorAction SilentlyContinue |

    ForEach-Object {
        $filePath = $_.FullName;
        $fileName = $_.FullName.Replace('/', '_').Replace('\', '_').Replace(':', '');
        $fileName = $fileName.Substring($fileName.IndexOf("_Tests_") + 7).Replace("_Logs_Text_", "-");
        Push-AppveyorArtifact $_.FullName -FileName $fileName
    }

    Write-Host "Logs uploaded."
init:
- git config --global core.autocrlf true
build_script:
- dotnet run --project CodeCakeBuilder -nointeraction
